### PR TITLE
Use .npmignore instead of files in package.json

### PR DESCRIPTION
**Pull request by benhoneywill**
The files whitelist means that whenever a new file is added we need to remember to include the file. Specifically the `.d.ts` file was not added to the files array.

Using the .npmignore blacklist we can exclude the files we don't want included in the final install while, not having to worry about including new files in the future

### CODE REVIEW

**Review by js1300 — CHANGES_REQUESTED** [review]
If we're going to blacklist then I would say that the git ignore should be there along with the readme, I'm not sure what the done thing is with licences in npm packages.

I don't think we really should switch from whitelisting to blacklisting, any new file added to the project, outside of the examples folder, will now end up in the npm package.

**Comment by benhoneywill** [comment]
Npm will never not include the readme even if you blacklist it. Licences are usually included.

But fair enough. We could switch the `files` key to a glob pattern like `files: ['src/**/*']` to only include the src directory. That way we wouldn't have this issue again where something is not added to the array, but files in the root will also not be included?

**Comment by js1300** [comment]
Thanks for the clarification about the readme and licence.

I like your proposed solution, it stops updating the list from becoming laborious when we add files to the source but protects files from the root and new folders being added to the package by default.

**Comment by benhoneywill** [comment]
OK, done! :)

**Review by js1300 — APPROVED** [review]

**Pull request merged**
